parameters:
#    galileo_simple_bet_model.example.class: Galileo\SimpleBet\ModelBundle\Example

services:
#    galileo_simple_bet_model.example:
#        class: %galileo_simple_bet_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
