Galileo\SimpleBet\ModelBundle\Entity\Bet:
  type: entity
  table: gsbm_bet
  id:
      id:
          type: integer
          generator:
              strategy: AUTO
  oneToOne:
      score:
          targetEntity: Galileo\SimpleBet\ModelBundle\Entity\Score
          joinColumn: score_id
  manyToOne:
      game:
          targetEntity: Galileo\SimpleBet\ModelBundle\Entity\Game
          inversedBy: bets
          joinColumn:
              name: game_id
              referencedColumnName: id

