Galileo\SimpleBet\ModelBundle\Entity\Player:
    type: entity
    table: gsbm_player
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            column: first_name
            nullable: true
        lastName:
            type: string
            column: last_name
            nullable: true
        displayName:
            type: string
            column: display_name
            nullable: true

    oneToMany:
        bets:
            targetEntity: Bet
            mappedBy: player