Galileo\SimpleBet\ModelBundle\Entity\TournamentPlayer:
    type: entity
    table: gsbm_tournament_player
    id:
        id:
            type: integer
            generator: { strategy: AUTO}
    manyToOne:
        player:
            targetEntity: Player
            inversedBy: tournaments
            joinColumn:
                name: player_id
                referencedColumnName: id
        tournament:
            targetEntity: Tournament
            mappedBy: tournament