version: '2'
services:
  web:
    image: galileo/php:5.6-xdebug-apache-advanced
    volumes:
      - './:/var/www/html'
      - './.docker/sites-enabled:/etc/apache2/sites-enabled'
    ports:
      - '80:80'
    links:
      - mysql
    extra_hosts:
      - 'symfony-local:127.0.0.1'
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: application
      MYSQL_PASSWORD: my_pass
