version: '2'
services:
  web:
    build: ./
    image: typer/dev
    volumes:
      - './:/var/www/html'
      - './.docker/sites-enabled:/etc/apache2/sites-enabled'
    ports:
      - '80:80'
    links:
      - mysql
    extra_hosts:
      - 'symfony-local:127.0.0.1'
  mysql:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ktotowygra
      MYSQL_USER: punter
      MYSQL_PASSWORD: hello_mate_how_are_you
