default:
  http_metas:
    content-type: text/html

  metas:
    title:        Typer mistrzostwa świata Brazylia 2014
    robots:       index, follow
    description:  Wytypuj sobie co chcesz
    keywords:     brazylia 2014, mistrzowa świata, world cup
    language:     pl

  stylesheets:    [blueprint/screen.css, world_cup_2014]

  javascripts:    []

  has_layout:     on
  layout:         euro2012
