galileo_simple_bet_main_homepage:
    pattern:  /
    defaults: { _controller: GalileoSimpleBetMainBundle:Default:index }

galileo_simple_bet_main_default:
    pattern:  /def
    defaults: { _controller: GalileoSimpleBetMainBundle:Default:default }
