homepage:
    pattern:  /
    defaults: { _controller: gsbm.controller.tournament:homeAction }

gsbm_tournament_view_game_bets:
    pattern:  /t/{tournamentId}-{gameId}
    defaults: { _controller: gsbm.controller.tournament:gameBetsAction }

gsbm_tournament_view:
    pattern:  /t/{tournamentId}
    defaults: { _controller: gsbm.controller.tournament:listAction }

gsbm_tournament_view_current_games:
    pattern:  /tournament/{tournamentId}/games
    defaults: { _controller: gsbm.controller.tournament:currentGamesAction }

gsbm_player_join_tournament:
    pattern:   /p/j/t/{tournamentId}
    defaults: { _controller: gsbm.controller.player:joinTournamentAction }

gsbm_bet_view:
    pattern: /bet/{gameId}
    defaults: { _controller: gsbm.controller.bet:betAction }

gsbm_player_tournament_bet_accuracy:
    pattern: /tournament/{tournamentId}/accuracy
    defaults: { _controller: gsbm.controller.statistics:playerTournamentAccuracyStatisticsView }