homepage:
    pattern:  /
    defaults: { _controller: gsbm.controller.tournament:homeAction }

gsbm_tournament_show_game_bets:
    pattern:  /t/{tournamentId}-{gameId}
    defaults: { _controller: gsbm.controller.tournament:gameBetsAction }

gsbm_tournament_show:
    pattern:  /t/{tournamentId}
    defaults: { _controller: gsbm.controller.tournament:listAction }

gsbm_player_join_tournament:
    pattern:   /p/j/t/{tournamentId}
    defaults: { _controller: gsbm.controller.player:joinTournament }

gsbm_game_bets:
    pattern:  /b/{gameId}
    defaults: { _controller: gsbm.controller.game:betsAction }