galileo_simple_bet_main_homepage:
    pattern:  /
    defaults: { _controller: galileo_simplebet_mainbundle.controller.tournamentcontroller:homeAction }

galileo_simple_bet_main_homepage:
    pattern:  /t/{tournamentId}
    defaults: { _controller: galileo_simplebet_mainbundle.controller.tournamentcontroller:listAction }