parameters:
    galileo_simplebet_mainbundle.controller.tournamentcontroller.class: Galileo\SimpleBet\MainBundle\Controller\TournamentController

services:
    galileo_simplebet_mainbundle.controller.tournamentcontroller:
        class: %galileo_simplebet_mainbundle.controller.tournamentcontroller.class%