parameters:
    gsbm.controller.tournamentcontroller.class: Galileo\SimpleBet\MainBundle\Controller\TournamentController
    gsbm.controller.gamecontroller.class: Galileo\SimpleBet\MainBundle\Controller\GameController

services:
    gsbm.controller.tournamentcontroller:
        class: %gsbm.controller.tournamentcontroller.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @templating
    gsbm.controller.gamecontroller:
        class: %gsbm.controller.gamecontroller.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @templating
