<?php
// auto-generated by sfPropelCrud
// date: 2008/05/19 09:02:18
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $typ->getId() ?></td>
</tr>
<tr>
<th>Gole1: </th>
<td><?php echo $typ->getGole1() ?></td>
</tr>
<tr>
<th>Gole2: </th>
<td><?php echo $typ->getGole2() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $typ->getStatus() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $typ->getUserId() ?></td>
</tr>
<tr>
<th>Mecz: </th>
<td><?php echo $typ->getMeczId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $typ->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $typ->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
&nbsp;<?php echo link_to('list', 'typy/list') ?>
