propel:
 typy_turniej:
  _attributes: 
    phpName: Turniej
  id:
  nazwa: { type: varchar, size: 50 }
  created_at:
  updated_at:
 
 typy_mecz:
  _attributes: 
    phpName: Mecz
  id:
  turniej_id:
  zespol1: { type: varchar(20), required: true }
  zespol2: { type: varchar(20), required: true }
  gole1: { type: integer, size: 2 }
  gole2: { type: integer, size: 2 }
  data: TIMESTAMP
  aktywny: { type: boolean }
  rozegrany: { type: boolean } 
  status: { type: integer, size: 2 }
  typy_ilosc: { type: integer }
  created_at:
  updated_at:
  
 typy_komentarze:
  _attributes:
    phpName: Komentarze
  id:
  user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  tytul:   { type: varchar, size: 255 }
  tresc:   { type: longvarchar }
  created_at:
   
 typy_typ:
  _attributes: 
    phpName: Typ
  id:
  user_id:   { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  mecz_id:
  gole1: { type: integer, size: 2 }
  gole2: { type: integer, size: 2 }
  status: { type: integer, size: 1 }
  punkty: { type: integer, size: 3 }
  created_at:
  updated_at:
  
 typy_punkty:
  _attributes: 
    phpName: Punkty
  id:
  punkty: { type: integer, size: 5 }
  turniej_id:
  user_id:    { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  created_at:
  updated_at:
   
 sf_guard_user_profile:
  _attributes: { phpName: sfGuardUserProfile }
  id:
  user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  first_name:  varchar(20)
  last_name:   varchar(20)
  email:       varchar(32)
  aktywny:     { type: integer, size: 1}
  birthday:    date
  pieniadze:   { type: integer, size: 2}